FROM nginx:alpine

COPY ../docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Copier les fichiers statiques
COPY . /usr/share/nginx/html

EXPOSE 80

# Démarrer Nginx
CMD ["nginx", "-g", "daemon off;"]